### ISSUE TITLE
Can I use jaeger-s3 with `production` strategy of jaeger? 

### ISSUE THREAD

**Issue by anarcher** [muhammadn/jaeger-s3#41]
Hi, I have a question about jaeger-s3. 
If I deploy jaeger with `production` strategy (separated from collector and query and with multiple collectors?), I can use the jaeger-s3 plugin with this deployment?
Thanks for the open sourcing of jaeger-s3! :->

**Comment by muhammadn** [comment]
@anarcher I am not sure about the question. Is this on redhat openshift? From what i understand, jaeger-s3 works like any other gRPC [plugins](https://www.jaegertracing.io/docs/1.23/deployment/).

**Comment by anarcher** [comment]
Thanks for replying :-) I understood it :-)
