### ISSUE TITLE
trace data is delayed by about 10m

### ISSUE THREAD

**Issue by devendrapal-ag** [muhammadn/jaeger-s3#51]
I have deployed Jaeger using the operator https://github.com/jaegertracing/helm-charts/tree/main/charts/jaeger-operator
 and I have integrated with S3 https://github.com/muhammadn/jaeger-s3.
I am able to see the trace in the Jeager-UI but the trace data is delayed by about 10m.
Do you have any idea?

**Comment by muhammadn** [comment]
@devendrapal-ag It's common for the delay but usually is it about 1 minute
