### ISSUE TITLE
updating to the latest Loki artifacts / schema v12

### ISSUE THREAD

**Issue by sherifkayad** [muhammadn/jaeger-s3#59]
Would there be a plan to update the used Loki artifacts to the latest versions and supporting schema v12? .. Also I noticed the latest release here is from Novemeber, 2021.

When do you plan to issue a new release?

**Comment by muhammadn** [comment]
@sherifkayad There is a lot of dependencies which requires updating and will break the current code. So there are a lot of things to work on at the moment.

Eventually we will work on this but there is no ETA.

Can you tell me why you need v12 schema and not using v11? If you really need us to prioritise this then feel free to contact our sales.

**Comment by sherifkayad** [comment]
@muhammadn not a must but just for the sake of improvement as the Loki project mentioned that this schema is more optimized to handle s3 rate limits.

Check the following links for more details:
- https://github.com/grafana/loki/releases/tag/v2.5.0
- https://github.com/grafana/loki/blob/main/CHANGELOG.md?plain=1#L158

**Comment by muhammadn** [comment]
@sherifkayad Thanks for point that out. But i don't think this would be urgent enough to get attention.

I'll see when i can do it as i have to prioritise some issues with our customers. 

The whole source code here is opensource and feel free to add those features in! ❤️

**Comment by muhammadn** [comment]
@sherifkayad We are working on version 2.0 which includes v12 schema based on loki 2.5.0. 

It's not released yet but we're using it in production to test out for real world use case.

**Comment by sherifkayad** [comment]
Sounds awesome! Thanks for the heads up

**Comment by muhammadn** [comment]
@sherifkayad version 2 is just released. closing this issue.
