### ISSUE TITLE
Retention Period

### ISSUE THREAD

**Issue by sherifkayad** [muhammadn/jaeger-s3#60]
How can one manage the desired retention period? let's assume I am only interested in keeping the trace data only for 14 days or say 30 days and then the data should be deleted from S3 .. how can we manage that?

**Comment by muhammadn** [comment]
This would be an interesting feature. Internally we leverage on loki (boltdb-shipper) which in turn leverages on cortex so to interface with s3.

We did work on the "compactor" - which is what you want but there still needs some work on this and we're still working out a new release.

**Comment by muhammadn** [comment]
@sherifkayad I've released v1.2.2 (sorry i mistakenly set the packages/docker to private and should be public), with a more complete implementation of the compactor.

More info on configuring retention is [here](https://grafana.com/docs/loki/latest/operations/storage/retention/).
