### ISSUE TITLE
Dead Links in Kustomize Config

### ISSUE THREAD

**Issue by loganrobertclemons** [muhammadn/jaeger-s3#80]
These links are no longer active:

resources:
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role.yaml
  - https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/cluster_role_binding.yaml

**Comment by muhammadn** [comment]
@loganrobertclemons Yes, we missed this. Thank you for reporting. I think for the next release we will remove Kubernetes example as it would change anyway.

Do check out the next release which would solve all the problems we had before.

**Comment by muhammadn** [comment]
@loganrobertclemons I've removed kubernetes configuration since it's irrelevant now. We should refer from the Jaeger docs which looks much simpler than before.
